[language-server.rust-analyzer.config.check]
command = "clippy"

[[rust]]
[config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

# use-grammars = { only = [ "rust", "c", "flare", "toml", ] }


[[language]]
name = "flare"
scope = "source.flare"
grammar = "flare"
injection-regex = "flare"
file-types = ["flare", "flr"]
comment-tokens = "#"
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "flare"
source = { git = "https://github.com/UPWRD1/tree-sitter-flare.git", rev = "1b464a4159bdd2f7578aa7fc76742fc476870591"}



